CLOUDFLARE_PROJECT_NAME = "STATELESS-REPORT"
CLOUDFLARE_ACCOUNT_ID = "eadcaeba6eea678b990f0f3e20421829"
CLOUDFLARE_API_TOKEN = "c1xDPKSXq4IxWv4m3g84YGgo82yXNYSWBoNMQRxN"
R2_ACCESS_KEY_ID = "620f93f772ab3f8a8403ecb78f268425"
R2_SECRET_ACCESS_KEY = "ca8259d261bae2d4ed5c3a34d948374495fef12be3ce2a18eae68ef9e1f7eaa0"
R2_PUBLIC_BUCKET = "statelessreport"
